# -*- coding: utf-8 -*-
"""DopplerDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKJz0qBKicCVSDfMqrxFlr0MC7Sy33v-

# **Libraries**
"""

import os
import pickle
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import math
import random
import pandas as pd
import sys

"""# **load_sample**"""

def load_sample(file_path: str) -> torch.Tensor:
    with open(file_path, 'rb') as f:
        data = pickle.load(f)

    try:
        # Attempt to convert to numpy array of floats directly
        # This will raise a ValueError if elements are non-numeric strings
        data_np = np.array(data, dtype=float)
        return torch.from_numpy(data_np).float()
    except ValueError:
        # If direct conversion to float fails (e.g., due to non-numeric strings)
        return np.array(data) # Return the data as a NumPy array (which might have dtype=object or dtype=str)
    except TypeError as e:
        # Catch other type errors during np.array or torch.from_numpy
        return data

"""# **load_files**"""

def load_files(main_path: str,
               list_dir: list,
               filename_antennas: str,
               init_files: int,
               end_files: int) -> np.ndarray:

  subjects_path = [os.path.join(main_path, subject) for subject in list_dir]
  filename_path = [os.path.join(subject, filename_antennas) for subject in subjects_path]
  filename_path = filename_path[init_files:end_files]
  files = [load_sample(filename) for filename in filename_path]
  files = np.concatenate(files).flatten()

  # Clean hardcoded paths from Docker if running locally
  if len(files) > 0 and isinstance(files[0], str):
      files = np.array([f.replace("/app/dataset/data/doppler_traces", main_path) for f in files])

  return files

"""# **class DopplerDataset**"""

class DopplerDataset(Dataset):

    def __init__(self,
                 file_paths: list,
                 labels_source: list,
                 mean = 0.,
                 std = 0.1,
                 scale_range=(0.8, 1.2),
                 ratio=0.1,
                 dim=1,
                 activity_map: dict = None,
                 fullvram: bool = False) -> None:

        """
        Input data

        file_paths = list of doppler raw data
        labels_sources = list of labels associated to raw data
        mean, std = values associated to gaussian noise
        scale_range = associated to random scale
        ratio = associated to random masking
        dim = associated to masking dimension

        """

        super(DopplerDataset, self).__init__()

        self.file_paths = file_paths
        # self.transform = transform
        self.labels = {}
        self.mean = mean
        self.std = std
        self.scale_range = scale_range
        self.ratio = ratio
        self.dim = dim

        if isinstance(labels_source, (list, np.ndarray)):
            # If labels_source is already a list or numpy array, process it directly
            label_data_processed = labels_source

            if len(labels_source) != len(self.file_paths):
                print(f"Warning: Number of labels ({len(labels_source)}) does not match number of provided file paths ({len(self.file_paths)}). This might lead to incorrect label assignment if order does not correspond.")

            # Map labels to file paths by index
            for i, file_path in enumerate(self.file_paths):
                if i < len(labels_source):
                    label_value = labels_source[i]
                    if isinstance(label_value, str):
                        self.labels[file_path] = activity_map[label_value]
                    elif isinstance(label_value, (int, np.integer, float)): # Added float for numeric labels
                        self.labels[file_path] = int(label_value) # Convert float labels to int
                    else:
                        print(f"Warning: Skipping label at index {i} with unexpected type {type(label_value)}. Expected string or numeric.")
                else:
                    print(f"Warning: No label found for file path {file_path} at index {i}. Skipping this sample.")


        else:
            raise TypeError(f"Unsupported type for labels_source: {type(labels_source)}. Expected a list of labels or a path to a pickled label file.")

        # Verify that all file_paths have corresponding labels
        self.data_items = []
        for path in self.file_paths:
            if path in self.labels:
                self.data_items.append({'file_path': path, 'label': self.labels[path]})
            else:
                print(f"Warning: No label found for {path}. Skipping this sample.")
        
        self.fullvram = fullvram
        self.vram_cache = []
        if self.fullvram:
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            print(f"Preloading dataset into {device} VRAM...")
            for item in tqdm(self.data_items, desc="Preloading to VRAM"):
                sample = load_sample(item['file_path'])
                if isinstance(sample, np.ndarray):
                    sample = torch.from_numpy(sample).float()
                elif not isinstance(sample, torch.Tensor):
                    raise TypeError(f"Expected numpy array or torch tensor, got {type(sample)}")
                self.vram_cache.append(sample.to(device))

    ######################################### APPLY TRANSFORMS #####################################

    def gaussian_noise(self, tensor: torch.Tensor) -> torch.Tensor:
            # tensor shape is (sequence_length, features) or (num_segments, segment_length, features)
            return tensor + (torch.randn(tensor.size(), device=tensor.device) * self.std + self.mean)

    def random_scale(self, tensor: torch.Tensor) -> torch.Tensor:
            # tensor shape is (sequence_length, features) or (num_segments, segment_length, features)
            scale_factor = random.uniform(self.scale_range[0], self.scale_range[1])
            return tensor * scale_factor

    def random_masking(self, tensor: torch.Tensor) -> torch.Tensor:
            if self.ratio <= 0: return tensor
            
            # True block masking (Cutout / SpecAugment style)
            # Mask out a random block of size proportional to self.ratio in both Time and Frequency
            if tensor.dim() == 2:
                time_steps, freq_bins = tensor.shape
                
                # Determine mask sizes
                t_mask_size = max(1, int(time_steps * self.ratio * 2.0))
                f_mask_size = max(1, int(freq_bins * self.ratio * 2.0))
                
                # Choose random start indices
                t_start = torch.randint(0, max(1, time_steps - t_mask_size), (1,)).item()
                f_start = torch.randint(0, max(1, freq_bins - f_mask_size), (1,)).item()
                
                # Apply mask
                tensor[t_start:t_start + t_mask_size, :] = 0.
                tensor[:, f_start:f_start + f_mask_size] = 0.
                
            return tensor

    def compose(self, img: torch.Tensor) -> torch.Tensor:
        self.img = img

        return self.random_masking(self.random_scale(self.gaussian_noise(self.img)))

    ################################################################################################

    def __len__(self):
        return len(self.data_items)

    def __getitem__(self, idx: int) -> tuple:
        item = self.data_items[idx]
        label = item['label']

        if self.fullvram:
            sample_data = self.vram_cache[idx].clone() # Clone to avoid in-place modification during transforms
        else:
            file_path = item['file_path']
            sample_data = load_sample(file_path)
        if isinstance(sample_data, np.ndarray):
            sample_data = torch.from_numpy(sample_data).float()
        elif not isinstance(sample_data, torch.Tensor):
            raise TypeError(f"Expected numpy array or torch tensor, got {type(sample_data)}")

        # --- INSTANCE NORMALIZATION ---
        # Normalize each sample independently to zero mean and unit variance.
        # This makes the model robust to varying absolute signal power across different subjects (S6, S7).
        mean_val = sample_data.mean()
        std_val = sample_data.std()
        if std_val > 1e-6:
            sample_data = (sample_data - mean_val) / std_val
        else:
            sample_data = sample_data - mean_val
        # ------------------------------

        sample_data = self.compose(sample_data)

        return sample_data, torch.tensor(label, dtype=torch.long)